compute-resource:
  refresh: 0.1
  files:
    scheme: ssh
    location: cerise-integration-test-slurm:22
    username: xenon
    password: javagat
    path: /home/xenon/.cerise

  jobs:
    scheme: slurm
    location: cerise-integration-test-slurm:22
    username: xenon
    password: javagat
