compute-resource:
  refresh: 0.1
  files:
    protocol: sftp
    location: cerise-integration-test-slurm:22
    credentials:
      username: xenon
      password: javagat
    path: /home/xenon/.cerise

  jobs:
    protocol: ssh
    location: cerise-integration-test-slurm:22
    credentials:
      username: xenon
      password: javagat
    scheduler: slurm
