client-file-exchange:
  store-location-service: local:///tmp/cerise_files
  store-location-client: local:///tmp/cerise_files

database:
  file: run/cerise.db

logging:
  file: /var/log/cerise/cerise_backend.log
  level: INFO

pidfile: run/cerise_backend.pid

rest-service:
  hostname: 127.0.0.1           # Set to 0.0.0.0 to listen on external interfaces as well
  port: 29593
