compute-resource:
  files:
    scheme: local
    path: /tmp/simple_cwl_xenon_service

  jobs:
    scheme: local

client-file-exchange:
  store-location-service: file:///tmp/simple_cwl_xenon_service_files
  store-location-client: file:///tmp/simple_cwl_xenon_service_files

database:
  file: run/scxs.db

pidfile: run/scxs_backend.pid

rest-service:
  hostname: 127.0.0.1           # Set to 0.0.0.0 to listen on external interfaces as well
  port: 29593
