client-file-exchange:
  store-location-service: file:///tmp/simple_cwl_xenon_service_files
  store-location-client: file:///tmp/simple_cwl_xenon_service_files

database:
  file: run/scxs.db

logging:
  file: /var/log/scxs/scxs_backend.log
  level: INFO

pidfile: run/scxs_backend.pid

rest-service:
  hostname: 127.0.0.1           # Set to 0.0.0.0 to listen on external interfaces as well
  port: 29593
