compute-resource:
  files:
    scheme: local
    path: /home/simple_cwl_xenon_service/run

  jobs:
    scheme: local

client-file-exchange:
  store-location-service: /home/simple_cwl_xenon_service/run/files
  store-location-client: http://localhost:29594/

database:
  file: /home/simple_cwl_xenon_service/run/scxs.db

rest-service:
  hostname: 0.0.0.0           # Set to 0.0.0.0 to listen on external interfaces as well
  port: 29593
