client-file-exchange:
  store-location-service: file:///home/cerise/run/files
  store-location-client: http://localhost:29594/

database:
  file: /home/cerise/run/cerise.db

logging:
  file: /var/log/cerise/cerise_backend.log
  level: INFO

pidfile: /home/cerise/run/cerise_backend.pid

rest-service:
  hostname: 0.0.0.0           # Set to 0.0.0.0 to listen on external interfaces as well
  port: 29593
