compute-resource:
  files:
    scheme: local
    location:               # TODO: allow leaving these out completely
    path: /tmp/simple_cwl_xenon_service
    credential:
    properties:

  jobs:
    scheme: local
    location:
    credential:
    properties:

client-file-exchange:
  store-location-service: file:///home/webdav/files
  store-location-client: http://localhost:29594/

rest-service:
  hostname: 0.0.0.0           # Set to 0.0.0.0 to listen on external interfaces as well
  port: 29593
